#include "cprintf.h"
int main()
{
	cprintf("%s %s %d %s %d\n", "{black}ehibfwvjbkuiew{red}fgLCUEUIGvli{white}uEGFVLI{green}ILWR{yellow}Hvbi{bule}HVIBU{purple}WBHC{cyan}wvlrjvkjnvkjdcbvljb{clear}cjbskdjlvbjasf", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 114514, "efbwevohaerhgkvfewugfagawhlgfigriywgjvwejhciwgihegjyvwrisavclhhahscvhvahwhjvbewvcjhkcvheqivchkvkhcbiqhbcjkqbkhbqhbhlecbqlehvhqwbvkhbkhlbvkbvljahbkhcvbklvbkbabehkavbkahbvkhavbakhebekjabhhgvcuiweryiagvhgweyhgviyacwhgvlyiwgviywgyihlwgiyywhgviywgyiwgcjtycujgcjuttugggggggukkuyutyktfytgfyyfuktggfllyryhgwygyiwryrwyiyirliaiirwyayiwgiyrryiirryhihoijovihoiwhoweoweh", 514);
}